services:
  - type: web
    runtime: python
    name: shl-fastapi
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GOOGLE_API_KEY
        sync: false # You'll add it manually in the dashboard
